### ISSUE TITLE
How to install RSS Box? 

### ISSUE THREAD

**Issue by alyusufMurtadha** [stefansundin/rssbox#62]
Hi,
How to install RSS Box?
because I tried to upload the script to my site..

thanks

**Comment by pucmelak** [comment]
This worked for me:

install docker - https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04

pull - `docker pull stefansundin/rssbox`

create ".env" file, template of file is here - https://github.com/stefansundin/rssbox/blob/master/.dockerenv.example

`sudo docker run -i -t -p 3000:3000 --env-file=PATH-TO-YOUR-.ENV-FILE`

Done. RSSbox is running on port 3000.

**Comment by faveoled** [comment]
@pucmelak I think you missed `stefansundin/rssbox` in `docker run`
